SCRIPT = {
"1.1": [
 "Hi Krishna! Today we are going to understand physics properly, so you can remember it in the exam. Let's start with physical quantities. A physical quantity is anything you can measure, like length, mass, time, or temperature.",
 "A physical quantity always has two parts: a number, and a unit. Five on its own means nothing. Five kilograms does. Watch the unit lock in.",
 "Quick guess before I show you. Which unit would you use to measure the mass of a bag of rice?",
 "Now it is your turn. Tap a unit, then tap the quantity it belongs to. If you get one wrong, I will give you a hint.",
 "Remember: a physical quantity is a number plus a unit. Length in metres, mass in kilograms, time in seconds, and volume in cubic centimetres."],
"1.2": [
 "When you read a measuring cylinder, the water surface curves. That curve is called the meniscus. Always put your eye level with the bottom of the curve.",
 "Move the eye up and down. See how the reading changes? Only when your eye is level do you get the true reading. Can you find it?",
 "Converting units is like climbing a ladder. A kilometre is one thousand metres, and a metre is one hundred centimetres. Going to a smaller unit, the number gets bigger, so you multiply. Going to a bigger unit, the number gets smaller, so you divide.",
 "Try some conversions. Pick the units and type a number, and watch the ladder tell you whether to multiply or divide.",
 "Remember: eye level with the bottom of the meniscus. Smaller unit, bigger number. And repeat a measurement a few times and take the average, to be more accurate."],
"1.3": [
 "Speed tells you how far something travels every second. Speed equals distance divided by time.",
 "If a car goes one hundred and fifty metres in ten seconds, we divide one hundred and fifty by ten, which gives fifteen metres per second. Always write the unit.",
 "Which is faster, twenty metres per second, or sixty kilometres per hour? Think carefully, you will need to convert.",
 "Change the distance and the time with the sliders, and watch the car. Then press the button to change kilometres per hour into metres per second.",
 "Remember: speed is distance divided by time. To go from kilometres per hour to metres per second, divide by three point six. To go back, multiply by three point six."],
"2.1": [
 "Here is a cyclist riding along a road. Below, a graph draws his distance from the start, second by second. Watch the line.",
 "When he stops, the line goes flat, because his distance is not changing. When he rides faster, the line gets steeper. Steeper means faster.",
 "Which graph shows a cyclist who rides slowly, then stops, then rides faster?",
 "Now you ride! Press slow, fast, or stop, and watch the graph grow. Try all three.",
 "Remember: on a distance time graph, a flat line means stopped, and a steeper line means faster. The gradient is the speed."],
"2.2": [
 "Let's read a real graph, like the one in your test. To find a speed, choose a straight section, find how far up it goes, and divide by how far across.",
 "For example, from thirty to fifty seconds, the distance goes from sixty to one hundred and forty metres. That is eighty metres in twenty seconds, which is four metres per second.",
 "For the whole trip, which do we use to find the average speed?",
 "Tap any two points on the graph, and I will work out the speed between them. Try three different sections.",
 "Remember: speed is rise over run. Average speed is total distance divided by total time, including any time spent stopped."],
"2.3": [
 "Now the graph shows velocity, which is speed in a direction. Here a car speeds up, drives steadily, and then slows down. Watch the graph.",
 "Careful! Here, a flat line does not mean stopped. It means a steady speed. The slope tells us how quickly the speed is changing. That is called acceleration.",
 "A car goes from zero to twenty metres per second in ten seconds. What is its acceleration?",
 "Drive the car with the throttle and the brake. Watch how the slope of the graph changes.",
 "Remember: on a velocity time graph, the slope is the acceleration, and a flat line is a constant velocity. Acceleration is the change in velocity divided by the time, in metres per second squared."],
"2.4": [
 "There is a secret hidden under every velocity time graph. The area under the line is the distance travelled.",
 "Split the shape into easy pieces: a triangle, a rectangle, and another triangle. The area of a rectangle is base times height. The area of a triangle is half times base times height.",
 "A car goes at twenty metres per second for twenty seconds. How far does it travel?",
 "Now add up the three areas to find the total distance. Tap each piece to reveal its area, then type the total.",
 "Remember: the area under a velocity time graph is the distance travelled. Rectangle: base times height. Triangle: half base times height."],
"3.1": [
 "Look at these two cubes. They are the same size, but one is foam and one is lead. The lead feels much heavier.",
 "Zoom in. In lead, the particles are packed tightly, so there is a lot of mass in every cubic centimetre. In foam, the particles are spread out. That is density: how much mass there is in each unit of volume.",
 "A block has a mass of two hundred grams and a volume of fifty cubic centimetres. What is its density?",
 "Pick different materials and look at their densities. Then use the triangle: cover the quantity you want to find, and it shows you the formula.",
 "Remember: density equals mass divided by volume. The units are grams per cubic centimetre, or kilograms per cubic metre."],
"3.2": [
 "To find the density of a regular block, measure the length, width, and height, and multiply them to get the volume. Then divide the mass by the volume.",
 "A stone has no neat sides, so we use displacement. The stone pushes aside its own volume of water. The rise in the water level is the volume of the stone.",
 "Why can't we use a ruler to find the volume of a stone?",
 "Weigh the stone, then lower it into the cylinder. Read the new level, work out the volume, and then the density.",
 "Remember: for an irregular solid, the volume is the final reading minus the starting reading. Then density equals mass divided by volume."],
"3.3": [
 "Will it float or sink? Compare the density of the object with the density of the liquid. If the object is less dense, it floats. If it is more dense, it sinks.",
 "Water has a density of one gram per cubic centimetre. So cork and wood float, but iron and lead sink. A ship floats because it is hollow, so its average density is less than water.",
 "Ice has a density of zero point nine two. Will it float or sink in water?",
 "Choose an object, guess whether it floats or sinks, and then drop it into the tank.",
 "Here is another trick. Squeeze a syringe full of air. The mass of the air stays the same, but the volume gets smaller, so the density goes up. Try it.",
 "Remember: an object floats if it is less dense than the liquid, and sinks if it is more dense. Squeeze a gas, and its density increases."],
"4.1": [
 "Everything is made of tiny particles, and they are always moving. The hotter something is, the faster its particles move. Drag the slider to see.",
 "Thermal energy always flows from hot to cold. Watch the hot block touch the cold block. Energy flows across until they are at the same temperature.",
 "A hot cup of tea is sitting in a cool room. Which way does the thermal energy flow?",
 "Heat up the left block, then bring the blocks together. Watch the temperatures meet.",
 "Remember: thermal energy flows from hot to cold. The hotter something is, the faster its particles move."],
"4.2": [
 "Conduction is how thermal energy moves through solids. The particles cannot move around, but they vibrate. Watch the hot end shake its neighbours, who shake the next ones, like a row of dominoes.",
 "In metals this happens quickly, so metals are good conductors. In wood, plastic and glass it is slow, so they are poor conductors, called insulators.",
 "Four rods are heated at one end: copper, iron, glass, and wood. There are pins stuck on with wax. Which rod's pin falls off first?",
 "Light the heat source, and watch the wax melt. You can speed up time if you like.",
 "Remember: conduction happens in solids, as particles vibrate and pass on energy. Metals are the best conductors. For a fair test, keep the length and thickness of the rods the same."],
"4.3": [
 "Convection happens in liquids and gases, because their particles can move around. Look at the water in this beaker, with a little purple crystal at the bottom.",
 "When the water is heated, its particles spread out. The warm water is less dense than the cold water around it, so it rises. Cooler, denser water sinks to take its place. This loop is called a convection current.",
 "Why is the heating element in an electric kettle at the bottom?",
 "Turn the heater on and off. Watch the purple colour get carried around in the loop.",
 "Here are three places you see this every day. In a kettle, the element is at the bottom. In a fridge, the freezer is at the top, because cold air sinks. And warm air from a radiator rises towards the ceiling.",
 "Remember: warm fluid expands, becomes less dense, and rises. Cool fluid is denser, and sinks. Convection cannot happen in solids."],
"4.4": [
 "How does the Sun's energy reach us across empty space? Not by conduction or convection, because there are no particles in space. It travels by radiation, as infrared waves.",
 "Radiation does not need any particles at all. Every hot object gives it out, and the hotter it is, the more it gives out.",
 "Two cans hold hot water at eighty degrees Celsius. One is shiny silver, the other is matt black. Which one cools down faster?",
 "Choose a can surface and a mode: cooling down, or warming in the sun. Compare black, silver and white on the graph.",
 "Remember: radiation can travel through a vacuum. Dull black surfaces are the best at absorbing and giving out radiation. Shiny and white surfaces reflect it."],
"4.5": [
 "This is the star of the show: the vacuum flask. It is built to stop all three kinds of thermal energy transfer, so hot drinks stay hot, and cold drinks stay cold.",
 "Between the two glass walls is a vacuum. There are no particles, so no conduction and no convection through the gap. The walls are coated with shiny silver, so radiation is reflected back. And the stopper is plastic, a poor conductor, so very little escapes through the top.",
 "What would happen if the vacuum were replaced by air?",
 "Now test it yourself. Switch the features on and off, and watch the temperature of the hot drink. Find out which feature stops which method.",
 "Remember: the vacuum stops conduction and convection. The shiny silver walls reflect radiation. The plastic stopper is a poor conductor. Together they keep the temperature steady. And it works for cold drinks too, because it stops energy getting in."],
"4.6": [
 "Insulators are poor conductors. Many everyday things are designed to slow down thermal energy transfer. A woolly jumper traps air. A double glazed window has air or a vacuum between two layers of glass. And a saucepan has a plastic handle.",
 "Trapped air is a very poor conductor. And if it is trapped in tiny pockets, it cannot circulate, so convection is blocked as well.",
 "Why does a plastic pan handle stay cool?",
 "Match each everyday example to the method of transfer it is about.",
 "Remember: poor conductors are called insulators. Trapped air stops conduction and convection. Shiny surfaces reflect radiation."],
"4.7": [
 "In real life, it is rarely just one method. Look at this campfire. There are three things happening at once.",
 "The stick conducts heat to your hand. The air above the fire rises, by convection. And you feel the warmth on your face by radiation.",
 "When you sit beside a bonfire, which method is warming your face?",
 "Your turn. Tap each glowing spot and choose the method. Then try the cup of tea.",
 "Remember: conduction in solids, convection in liquids and gases, and radiation through anything, even a vacuum. Many everyday situations use more than one."],
"g": [
 "Hi Krishna! I am so glad you are here. Pick any scene, and let's learn some physics together.",
 "Yes! Well done.",
 "That's right, great job!",
 "Exactly. You've got it.",
 "Not quite. Let's look at why.",
 "Almost! Have a look at the explanation.",
 "Scene complete. Well done, Krishna!",
 "Final round! Twenty questions from all four topics. Take your time, and remember what we practised.",
 "All done! Let's see how you did.",
 "Brilliant work! You really know your physics.",
 "Good effort. Let's revisit the topics that are still tricky."],
}
