/* ===== 1.1 Digital footprint ===== */
SCENES.push({id:'1.1',act:'sec',title:'Your digital footprint',idea:'Active and passive footprints; being a good digital citizen',
 setup(ctx){
  const s=ctx.svg();const X={s,steps:[],cards:[]};
  const me=G(90,0);me.append(C(0,190,26,{fill:'#f1c9a5','stroke-width':2.5}),R(-26,216,52,90,{rx:12,fill:'var(--accent)'}),L(-12,306,-12,350),L(12,306,12,350));s.append(me);
  for(let i=0;i<8;i++){const x=150+i*38,y=330-i*20+(i%2?8:-4);const g=S('g',{opacity:0,transform:`translate(${x} ${y}) rotate(-20)`});g.append(S('ellipse',{cx:0,cy:0,rx:9,ry:15,fill:'#9aa7bd'}),S('ellipse',{cx:2,cy:-20,rx:6,ry:7,fill:'#9aa7bd'}));s.append(g);X.steps.push(g)}
  const cloud=S('g');cloud.append(S('path',{d:'M470 110Q470 70 515 72Q530 40 580 52Q625 40 650 75Q710 70 710 112Q710 150 660 150H520Q470 150 470 110Z',fill:'#e6eefb','stroke-width':3,stroke:'var(--ink)'}),T(590,108,'the internet',{'font-size':20,'font-family':'Fredoka,sans-serif'}),T(590,132,'stored for a long time',{'font-size':14,fill:'var(--muted)'}));s.append(cloud);
  [['Photo you posted','active',400,190],['Comment you wrote','active',596,190],['Sites you visited (cookies)','passive',400,270],['Where your phone has been','passive',596,270]].forEach(c=>{const g=S('g',{opacity:0});const col=c[1]==='active'?'var(--accent)':'#e08a2c';g.append(R(c[2],c[3],186,64,{rx:14,fill:'var(--paper)',stroke:col,'stroke-width':3}),T(c[2]+93,c[3]+27,c[0],{'font-size':13}),T(c[2]+93,c[3]+49,c[1]+' footprint',{'font-size':13,fill:col,'font-family':'Fredoka,sans-serif'}));s.append(g);X.cards.push(g)});
  X.think=S('g',{opacity:0});[['True','Is it true?'],['Kind','Is it kind?'],['Needed','Is it necessary?'],['Private','Is it safe to share?']].forEach((t,i)=>{X.think.append(R(60+i*180,140,160,120,{rx:16,fill:'var(--paper)',stroke:'var(--accent)','stroke-width':3}),T(140+i*180,185,t[0],{'font-size':26,'font-family':'Fredoka,sans-serif',fill:'var(--accent)'}),T(140+i*180,225,t[1],{'font-size':16}))});X.think.append(T(400,100,'Think before you post',{'font-size':26,'font-family':'Fredoka,sans-serif'}),T(400,310,'A good digital citizen is respectful, responsible and safe online.',{'font-size':18,fill:'var(--muted)'}));s.append(X.think);
  X.note=T(300,420,'',{'font-size':20,fill:'var(--accent)','font-family':'Fredoka,sans-serif'});s.append(X.note);
  X.show=m=>{[me,cloud,...X.steps,...X.cards].forEach(e=>e.setAttribute('opacity',m==='f'?1:0));X.think.setAttribute('opacity',m==='t'?1:0)};return X},
 steps:[
  {k:'watch',run(X,ctx){X.show('t');X.show('f');X.steps.forEach(g=>g.setAttribute('opacity',0));X.cards.forEach(g=>g.setAttribute('opacity',0));X.think.setAttribute('opacity',0);X.note.textContent='';X.steps.forEach((g,i)=>ctx.after(700+i*300,()=>g.setAttribute('opacity',1)));X.cards.forEach((g,i)=>ctx.after(3600+i*2600,()=>g.setAttribute('opacity',1)));ctx.after(14500,()=>X.note.textContent='Everything you do online leaves a trail')}},
  {k:'watch',run(X,ctx){X.show('t');X.note.textContent='';[...X.think.children].forEach(c=>c.setAttribute('opacity',0));[...X.think.children].forEach((c,i)=>ctx.after(300+i*500,()=>c.setAttribute('opacity',1)))}},
  {k:'predict',q:'You post a photo, then delete it one minute later. Can other people still have a copy?',opts:['Yes: someone may already have saved or shared it','No: deleting removes it everywhere','Only if you post it again','No: the internet forgets after an hour'],ans:0,why:'Once something is online, others can screenshot, save or share it. Think before you post.',run(X){X.show('f')}},
  {k:'try',build(X,ctx){X.show('f');
   matchGame(ctx.panel,{help:'Is it an active or a passive digital footprint?',items:[
    {label:'Posting a photo',to:'a',hint:'You chose to share it.'},{label:'Writing a comment on a video',to:'a',hint:'You deliberately posted it.'},{label:'Filling in an online form',to:'a',hint:'You typed the data yourself.'},
    {label:'A website records your visit using cookies',to:'p',hint:'It happens without you doing anything.'},{label:'An app tracks your location',to:'p',hint:'Collected in the background.'},{label:'A search engine stores your search history',to:'p',hint:'Stored automatically.'}],
    buckets:[{id:'a',label:'Active footprint (what you share)'},{id:'p',label:'Passive footprint (collected about you)'}],onDone:ctx.done})}},
  {k:'sum',take:'Your digital footprint is the trail of data you leave online. Active: what you post. Passive: data collected about you. Think before you post.',run(X){X.show('f')}}],
 quiz:[Q('t','Which is an ACTIVE digital footprint?',['Posting a comment','Cookies on a website','An app recording your location','A search engine saving your history'],0,'Active means you deliberately share it.'),
  Q('t','Which is a PASSIVE digital footprint?',['A website tracking your visits with cookies','Posting a photo','Sending an email','Writing a blog'],0,'Passive data is collected about you without you posting it.'),
  Q('t','What should you do before posting something online?',['Think whether it is true, kind and safe to share','Post it quickly','Check how many likes it gets','Delete it afterwards'],0,'Once online, it can be copied. Think before you post.')]});

/* ===== 1.2 Ethical online behaviour ===== */
SCENES.push({id:'1.2',act:'sec',title:'Behaving well online',idea:'Cyberbullying, plagiarism, copyright and netiquette',
 setup(ctx){
  const s=ctx.svg();const X={s};
  X.chat=S('g');X.chat.append(R(60,60,320,300,{rx:20,fill:'var(--paper)','stroke-width':3}),R(60,60,320,40,{rx:20,fill:'var(--accent)'}),T(220,88,'Group chat',{'font-size':18,fill:'var(--accent-ink)','font-family':'Fredoka,sans-serif'}));
  [['Nobody likes you. Quit the team!',130,'#fde3dc'],['Ha ha, look at your photo',200,'#fde3dc'],['I am telling everyone your secret',270,'#fde3dc']].forEach(m=>X.chat.append(R(80,m[1],250,50,{rx:14,fill:m[2],stroke:'var(--bad)','stroke-width':2}),T(205,m[1]+31,m[0],{'font-size':14})));
  X.acts=S('g');[['Do not reply',430,100],['Keep evidence (screenshot)',430,160],['Block and report',430,220],['Tell a trusted adult',430,280]].forEach((a,i)=>{const g=S('g',{opacity:0});g.append(R(a[1],a[2],330,46,{rx:12,fill:'var(--good-soft)',stroke:'var(--good)','stroke-width':2.5}),T(a[1]+165,a[2]+30,a[0],{'font-size':18}));X.acts.append(g)});
  X.doc=S('g');X.doc.append(R(40,80,220,170,{rx:12,fill:'var(--paper)','stroke-width':2.5}),T(150,106,'article on a website',{'font-size':14,fill:'var(--muted)'}));for(let i=0;i<5;i++)X.doc.append(L(60,130+i*22,240,130+i*22,{stroke:'var(--line)','stroke-width':6}));
  X.doc.append(R(520,80,240,170,{rx:12,fill:'var(--paper)','stroke-width':2.5}),T(640,106,'my homework',{'font-size':14,fill:'var(--muted)'}));for(let i=0;i<5;i++)X.doc.append(L(540,130+i*22,740,130+i*22,{stroke:'var(--line)','stroke-width':6}));
  X.doc.append(Pth('M270 165H510',{stroke:'var(--bad)','stroke-width':4,'stroke-dasharray':'8 8'}),T(390,150,'copy and paste',{'font-size':16,fill:'var(--bad)'}),R(580,170,150,44,{rx:8,fill:'none',stroke:'var(--bad)','stroke-width':4,transform:'rotate(-8 655 192)'}),T(655,200,'PLAGIARISM',{'font-size':20,fill:'var(--bad)','font-family':'Fredoka,sans-serif',transform:'rotate(-8 655 192)'}));
  X.fix=S('g');[['Use your own words',60],['Say where it came from',400],['Check the licence / ask',230]].forEach((f,i)=>{const g=S('g',{opacity:0});const x=i===0?60:i===1?290:520;g.append(R(x,290,220,70,{rx:14,fill:'var(--good-soft)',stroke:'var(--good)','stroke-width':2.5}),T(x+110,332,f[0],{'font-size':16}));X.fix.append(g)});
  s.append(X.chat,X.acts,X.doc,X.fix);
  X.show=m=>{X.chat.setAttribute('opacity',m==='c'?1:0);X.acts.setAttribute('opacity',m==='c'?1:0);X.doc.setAttribute('opacity',m==='d'?1:0);X.fix.setAttribute('opacity',m==='d'?1:0)};X.show('c');return X},
 steps:[
  {k:'watch',run(X,ctx){X.show('c');[...X.acts.children].forEach(g=>g.setAttribute('opacity',0));[...X.acts.children].forEach((g,i)=>ctx.after(3500+i*2300,()=>g.setAttribute('opacity',1)))}},
  {k:'watch',run(X,ctx){X.show('d');[...X.fix.children].forEach(g=>g.setAttribute('opacity',0));[...X.fix.children].forEach((g,i)=>ctx.after(5000+i*2500,()=>g.setAttribute('opacity',1)))}},
  {k:'predict',q:'You find a great picture online for your project. What should you do?',opts:['Check the licence and credit the creator','Use it; nobody will notice','Crop out the watermark','Say you drew it yourself'],ans:0,why:'Pictures are protected by copyright. Check the licence, ask permission if needed, and always say who made it.',run(X){X.show('d')}},
  {k:'try',build(X,ctx){X.show('c');const h=ctx.panel;
   const qs=[{q:'A classmate sends a mean message about another student. What is the best response?',o:['Forward it so others can see','Do not join in; tell a trusted adult or report it','Reply with an even meaner message','Say nothing and ignore it'],a:1,why:'Do not join in. Report it and tell a trusted adult.'},
    {q:'You paste a paragraph from a website into your essay without saying where it came from. This is…',o:['Plagiarism','Research','Referencing','Netiquette'],a:0,why:'Presenting other people\'s work as your own is plagiarism.'},
    {q:'A friend types in ALL CAPITALS and uses rude words in a group chat. What is good netiquette for you?',o:['Reply politely and respectfully','Reply in capitals too','Add rude comments back','Share their message elsewhere'],a:0,why:'Netiquette means being polite and respectful online.'}];
   let i=0;const host=H('div');h.append(host);
   const nxt=()=>{if(i>=qs.length){host.innerHTML='';host.append(H('div',{class:'fb good'},'All three handled well!'));ctx.done();return}const box=H('div');host.innerHTML='';host.append(H('p',{class:'hint'},'Situation '+(i+1)+' of '+qs.length),box);ask(qs[i],box,()=>{box.append(H('button',{class:'btn small',onclick:()=>{i++;nxt()}},i>=qs.length-1?'Finish':'Next situation'))})};nxt()}},
  {k:'sum',take:'Do not join in cyberbullying; report it. Do not plagiarise: use your own words and credit sources. Respect copyright. Be polite online.',run(X){X.show('d');[...X.fix.children].forEach(g=>g.setAttribute('opacity',1))}}],
 quiz:[Q('t','What should you do if you receive a cyberbullying message?',['Keep evidence and tell a trusted adult','Reply angrily','Delete your account and say nothing','Forward it to friends'],0,'Save evidence and get help from a trusted adult.'),
  Q('t','What is plagiarism?',['Passing off someone else\'s work as your own','Using a search engine','Writing in your own words','Creating a presentation'],0,'Copying work without crediting it is plagiarism.'),
  Q('t','What does copyright protect?',['The creator\'s ownership of their work','Your computer','Your passwords','Your internet speed'],0,'Copyright gives creators control over how their work is used.')]});

/* ===== 1.3 Data privacy ===== */
SCENES.push({id:'1.3',act:'sec',title:'Keeping your data private',idea:'Personal data and privacy settings',
 setup(ctx){
  const s=ctx.svg();const X={s,fields:[]};
  const card=S('g');card.append(R(60,50,330,350,{rx:22,fill:'var(--paper)','stroke-width':3}),C(130,110,32,{fill:'#f1c9a5','stroke-width':2.5}),T(225,104,'Krishna',{'font-size':22,'font-family':'Fredoka,sans-serif','text-anchor':'start'}),T(225,128,'my public profile',{'font-size':14,fill:'var(--muted)','text-anchor':'start'}));
  [['Name','Krishna'],['School','Inventure Academy'],['Phone','98xxxxxx12'],['Home address','12, Rose Street'],['Birthday','4 March 2012'],['Hobby','football']].forEach((f,i)=>{const y=170+i*38;const g=S('g',{opacity:0});g.append(R(80,y,290,30,{rx:8,fill:'var(--bg)',stroke:'var(--line)','stroke-width':1.5}),T(92,y+21,f[0]+':',{'font-size':14,fill:'var(--muted)','text-anchor':'start'}),T(210,y+21,f[1],{'font-size':14,'text-anchor':'start'}));card.append(g);X.fields.push(g)});s.append(card);
  const st=G(560,230);st.append(C(0,-20,26,{fill:'#c9ccd6','stroke-width':2.5}),S('path',{d:'M-34 100Q-34 20 0 20Q34 20 34 100Z',fill:'#444','stroke-width':2.5,stroke:'var(--ink)'}),T(0,130,'a stranger',{'font-size':16,fill:'var(--muted)'}));s.append(st);
  X.look=Pth('M400 230Q480 230 520 215',{stroke:'var(--bad)','stroke-width':4,'stroke-dasharray':'6 8'});X.look.setAttribute('opacity',0);s.append(X.look);X.bub=S('g',{opacity:0});X.bub.append(R(540,70,230,80,{rx:16,fill:'var(--bad-soft)',stroke:'var(--bad)','stroke-width':2.5}),T(655,105,'I know where you live',{'font-size':16}),T(655,129,'and when your birthday is...',{'font-size':14,fill:'var(--muted)'}));s.append(X.bub);
  X.set=S('g',{opacity:0});X.set.append(T(660,300,'Privacy settings',{'font-size':20,'font-family':'Fredoka,sans-serif'}));['Public','Friends only','Private'].forEach((l,i)=>{X.set.append(R(520+i*0,320+i*34,0,0,{}),R(540,320+i*34,240,28,{rx:14,fill:i===1?'var(--accent)':'var(--paper)','stroke-width':2.5}),T(660,339+i*34,l,{'font-size':16,fill:i===1?'var(--accent-ink)':'var(--ink)'}))});s.append(X.set);
  X.note=T(225,430,'',{'font-size':19,fill:'var(--accent)','font-family':'Fredoka,sans-serif'});s.append(X.note);return X},
 steps:[
  {k:'watch',run(X,ctx){X.fields.forEach((f,i)=>{f.setAttribute('opacity',0);ctx.after(600+i*900,()=>f.setAttribute('opacity',1))});X.look.setAttribute('opacity',0);X.bub.setAttribute('opacity',0);X.set.setAttribute('opacity',0);ctx.after(7000,()=>{X.look.setAttribute('opacity',1);X.bub.setAttribute('opacity',1)});X.note.textContent='Personal data = information about you'}},
  {k:'watch',run(X,ctx){X.fields.forEach(f=>f.setAttribute('opacity',1));X.look.setAttribute('opacity',0);X.bub.setAttribute('opacity',0);X.set.setAttribute('opacity',0);ctx.after(800,()=>X.set.setAttribute('opacity',1));X.note.textContent='Share the minimum. Check your privacy settings.'}},
  {k:'predict',q:'Which of these is safest to put on a public profile?',opts:['Your favourite colour','Your home address','Your phone number','Your password'],ans:0,why:'A favourite colour reveals nothing risky. Addresses, phone numbers and passwords must stay private.',run(X){X.fields.forEach(f=>f.setAttribute('opacity',1));X.look.setAttribute('opacity',0);X.bub.setAttribute('opacity',0);X.set.setAttribute('opacity',0);X.note.textContent=''}},
  {k:'try',build(X,ctx){X.fields.forEach(f=>f.setAttribute('opacity',1));X.set.setAttribute('opacity',0);X.note.textContent='';
   matchGame(ctx.panel,{help:'Is it safe to share publicly, or should it stay private?',items:[
    {label:'Favourite hobby',to:'s',hint:'Low risk.'},{label:'Favourite colour',to:'s',hint:'Harmless.'},{label:'Home address',to:'p',hint:'Strangers could find you.'},{label:'Phone number',to:'p',hint:'Could be misused.'},{label:'Passwords',to:'p',hint:'Never share a password.'},{label:'Full date of birth',to:'p',hint:'Used to steal identities.'}],
    buckets:[{id:'s',label:'Safe to share'},{id:'p',label:'Keep private'}],onDone:ctx.done})}},
  {k:'sum',take:'Personal data should be kept private: address, phone number, passwords, full date of birth. Use privacy settings and share the minimum.',run(X){X.fields.forEach(f=>f.setAttribute('opacity',1));X.set.setAttribute('opacity',1);X.note.textContent=''}}],
 quiz:[Q('t','Which information should you keep private?',['Your home address','Your favourite sport','Your favourite colour','Your favourite song'],0,'Your address could let strangers find you.'),
  Q('t','What are privacy settings used for?',['Controlling who can see your information','Making your computer faster','Deleting viruses','Increasing storage'],0,'They let you choose who sees what you share.'),
  Q('t','Which is the best rule for sharing personal data?',['Share only what is necessary','Share everything with friends','Share it all in public','Share only on weekends'],0,'Share the minimum.')]});
