/* ===== 4.1 The design thinking process ===== */
const DT=[{n:'Empathise',c:'#e5484d',d:'Understand the people you are designing for'},{n:'Define',c:'#e0911c',d:'State the problem clearly'},{n:'Ideate',c:'#2faa4a',d:'Come up with lots of ideas'},{n:'Prototype',c:'#2f64d8',d:'Build a quick, simple model'},{n:'Test',c:'#8a63d2',d:'Try it with users and learn'}];
SCENES.push({id:'4.1',act:'cad',title:'The design thinking process',idea:'Empathise, Define, Ideate, Prototype, Test',
 setup(ctx){
  const s=ctx.svg();const X={s,nodes:[]};const cx=400,cy=235,R_=150;
  DT.forEach((d,i)=>{const a=(-90+i*72)*Math.PI/180,x=cx+R_*Math.cos(a)*1.25,y=cy+R_*Math.sin(a);const g=G(x,y);g.append(C(0,0,46,{fill:d.c,'stroke-width':3}),T(0,6,String(i+1),{'font-size':30,fill:'#fff','font-family':'Fredoka,sans-serif'}),T(0,74,d.n,{'font-size':19,'font-family':'Fredoka,sans-serif'}));g.setAttribute('opacity',0);s.append(g);X.nodes.push({g,x,y})});
  X.arrows=S('g',{opacity:0});X.nodes.forEach((n,i)=>{const m=X.nodes[(i+1)%5];if(i===4)return;const dx=m.x-n.x,dy=m.y-n.y,l=Math.hypot(dx,dy),ux=dx/l,uy=dy/l;X.arrows.append(Pth(`M${n.x+ux*52} ${n.y+uy*52}L${m.x-ux*58} ${m.y-uy*58}`,{stroke:'var(--muted)','stroke-width':4}),S('polygon',{points:'0,-8 16,0 0,8',fill:'var(--muted)',transform:`translate(${m.x-ux*58} ${m.y-uy*58}) rotate(${Math.atan2(dy,dx)*180/Math.PI}) translate(-14 0)`}))});s.insertBefore(X.arrows,s.firstChild);
  const t=X.nodes[4],d3=X.nodes[2],d4=X.nodes[3];X.loop=S('g',{opacity:0});X.loop.append(Pth(`M${t.x-30} ${t.y+50}Q${(t.x+d3.x)/2} ${t.y+130} ${d3.x+20} ${d3.y+60}`,{stroke:'#e5484d','stroke-width':4,'stroke-dasharray':'9 7'}),S('polygon',{points:'0,-8 16,0 0,8',fill:'#e5484d',transform:`translate(${d3.x+20} ${d3.y+60}) rotate(-70) translate(-8 0)`}),T(400,425,'improve and go round again',{'font-size':18,fill:'#e5484d','font-family':'Fredoka,sans-serif'}));s.append(X.loop);
  X.mid=T(cx,cy-6,'Design thinking',{'font-size':22,'font-family':'Fredoka,sans-serif',fill:'var(--accent)'});X.mid2=T(cx,cy+22,'',{'font-size':15,fill:'var(--muted)'});s.append(X.mid,X.mid2);
  X.hi=i=>X.nodes.forEach((n,k)=>n.g.setAttribute('opacity',i==null?1:(k===i?1:.35)));X.reset=()=>{X.nodes.forEach(n=>n.g.setAttribute('opacity',0));X.arrows.setAttribute('opacity',0);X.loop.setAttribute('opacity',0);X.mid.textContent='Design thinking';X.mid2.textContent=''};return X},
 steps:[
  {k:'watch',run(X,ctx){X.reset();DT.forEach((d,i)=>ctx.after(700+i*2700,()=>{X.nodes.forEach((n,k)=>n.g.setAttribute('opacity',k<=i?(k===i?1:.6):0));X.arrows.setAttribute('opacity',1);X.mid.textContent=d.n;X.mid2.textContent=d.d}));ctx.after(14700,()=>{X.hi(null);X.mid.textContent='Design thinking';X.mid2.textContent=''})}},
  {k:'watch',run(X,ctx){X.reset();X.hi(null);X.arrows.setAttribute('opacity',1);X.mid2.textContent='';ctx.after(1200,()=>{X.loop.setAttribute('opacity',1);X.mid.textContent='Iterate';X.mid2.textContent='Fail early, learn fast'})}},
  {k:'predict',q:'A designer interviews students about how hard it is to carry heavy school bags. Which stage is this?',opts:['Empathise','Prototype','Test','Ideate'],ans:0,why:'Talking to the users to understand their problems is the Empathise stage.',run(X){X.reset();X.hi(null);X.arrows.setAttribute('opacity',1)}},
  {k:'try',build(X,ctx){X.reset();X.hi(null);X.arrows.setAttribute('opacity',1);
   matchGame(ctx.panel,{help:'Which stage is each activity?',items:[
    {label:'Interview users about their problems',to:'e',hint:'Understand the users first.'},{label:'Write a clear problem statement',to:'d',hint:'State the problem.'},{label:'Brainstorm lots of ideas and sketch them',to:'i',hint:'Generate ideas.'},{label:'Build a quick cardboard model',to:'p',hint:'A rough model.'},{label:'Ask users to try it and give feedback',to:'t',hint:'Find out what works.'}],
    buckets:[{id:'e',label:'Empathise'},{id:'d',label:'Define'},{id:'i',label:'Ideate'},{id:'p',label:'Prototype'},{id:'t',label:'Test'}],onDone:ctx.done})}},
  {k:'sum',take:'Empathise, Define, Ideate, Prototype, Test. Then improve the design and repeat. Design thinking is user-centred and iterative.',run(X){X.reset();X.hi(null);X.arrows.setAttribute('opacity',1);X.loop.setAttribute('opacity',1)}}],
 quiz:[Q('t','What is the first stage of design thinking?',['Empathise','Prototype','Test','Define'],0,'You start by understanding the users.'),Q('t','Building a quick cardboard model is which stage?',['Prototype','Define','Ideate','Empathise'],0,'A rough model is a prototype.'),
  Q('t','What should you do after testing a design?',['Improve it and repeat','Stop immediately','Delete the idea','Skip to the end'],0,'Testing shows what to improve; the process is a loop.'),Q('t','Brainstorming many ideas belongs to which stage?',['Ideate','Test','Define','Empathise'],0,'Generating lots of ideas is Ideate.')]});

/* ===== 4.2 Empathise, define and ideate ===== */
SCENES.push({id:'4.2',act:'cad',title:'From a person to a problem to ideas',idea:'User needs, a problem statement and brainstorming',
 setup(ctx){
  const s=ctx.svg();const X={s,quotes:[],notes:[]};
  const p=G(110,0);p.append(C(0,150,36,{fill:'#d9a066','stroke-width':2.5}),R(-34,186,68,110,{rx:14,fill:'#2f64d8'}),T(0,330,'Aarav, age 13',{'font-size':17,'font-family':'Fredoka,sans-serif'}),T(0,352,'a student',{'font-size':14,fill:'var(--muted)'}));s.append(p);
  ['"I keep losing my pens."','"My bag is always messy."','"I want something small."'].forEach((q,i)=>{const g=S('g',{opacity:0});g.append(R(200,70+i*66,250,52,{rx:14,fill:'var(--paper)','stroke-width':2.5}),T(325,102+i*66,q,{'font-size':15}));s.append(g);X.quotes.push(g)});
  X.def=S('g',{opacity:0});X.def.append(R(60,30,680,90,{rx:16,fill:'var(--accent-soft)',stroke:'var(--accent)','stroke-width':3}),T(400,66,'Problem statement',{'font-size':16,fill:'var(--accent)','font-family':'Fredoka,sans-serif'}),T(400,98,'Aarav needs a way to keep his pens together because he keeps losing them.',{'font-size':18}));s.append(X.def);
  ['pen pouch','clip-on holder','magnetic strip','pen on a string','desk organiser','robot pen finder'].forEach((t,i)=>{const x=80+(i%3)*230,y=170+Math.floor(i/3)*120;const g=S('g',{opacity:0,transform:`translate(${x} ${y}) rotate(${(i%2?3:-3)})`});g.append(R(0,0,190,90,{rx:8,fill:['#ffe58a','#ffc9d9','#c9f0d3','#cfe0ff','#ffe0b8','#e5d3ff'][i],'stroke-width':2}),T(95,52,t,{'font-size':17,'font-family':'Fredoka,sans-serif'}));s.append(g);X.notes.push(g)});
  X.cap=T(400,420,'',{'font-size':19,fill:'var(--accent)','font-family':'Fredoka,sans-serif'});s.append(X.cap);
  X.show=m=>{p.setAttribute('opacity',m==='e'?1:0);X.quotes.forEach(q=>q.setAttribute('opacity',m==='e'?1:0));X.def.setAttribute('opacity',m==='d'||m==='i'?1:0);X.notes.forEach(n=>n.setAttribute('opacity',m==='i'?1:0))};X.p=p;return X},
 steps:[
  {k:'watch',run(X,ctx){X.show('x');X.p.setAttribute('opacity',1);X.cap.textContent='Empathise: watch, ask and listen';X.quotes.forEach((q,i)=>{q.setAttribute('opacity',0);ctx.after(1500+i*2600,()=>q.setAttribute('opacity',1))});ctx.after(10500,()=>X.cap.textContent='Needs: keep pens together, small, tidy')}},
  {k:'watch',run(X,ctx){X.show('d');X.cap.textContent='Define: write the problem clearly';X.notes.forEach(n=>n.setAttribute('opacity',0));ctx.after(5500,()=>{X.cap.textContent='Ideate: lots of ideas, even wild ones';X.notes.forEach((n,i)=>ctx.after(i*700,()=>n.setAttribute('opacity',1)))});ctx.after(13000,()=>X.cap.textContent='Then choose using the user\'s needs')}},
  {k:'predict',q:'Which is the best problem statement?',opts:['Aarav needs a way to keep his pens together because he keeps losing them','Make a pen holder','Pens are blue','Design a bag'],ans:0,why:'A good problem statement names the user, their need, and why it matters. It does not jump to a solution.',run(X){X.show('x');X.cap.textContent=''}},
  {k:'try',build(X,ctx){X.show('i');X.cap.textContent='';const h=ctx.panel;
   const qs=[{q:'Which is a real user need for Aarav?',o:['A way to keep his pens together','A faster computer','A bigger classroom','More homework'],a:0,why:'It comes from what he told us: he keeps losing pens.'},{q:'During ideation, what is the best approach?',o:['Come up with lots of ideas, even unusual ones','Pick the first idea','Draw only one idea','Copy a friend'],a:0,why:'Quantity first: you can choose later.'},{q:'Aarav needs something cheap, light and small enough for his bag. Which idea fits best?',o:['A small clip-on pen holder','A heavy wooden desk organiser','A robot that finds pens','A large glass jar'],a:0,why:'It meets the needs: cheap, light, small.'}];
   let i=0;const host=H('div');h.append(host);const nxt=()=>{if(i>=qs.length){host.innerHTML='';host.append(H('div',{class:'fb good'},'Great design thinking!'));ctx.done();return}const box=H('div');host.innerHTML='';host.append(H('p',{class:'hint'},'Question '+(i+1)+' of '+qs.length),box);ask(qs[i],box,()=>{box.append(H('button',{class:'btn small',onclick:()=>{i++;nxt()}},i>=qs.length-1?'Finish':'Next question'))})};nxt()}},
  {k:'sum',take:'Empathise to find real needs. Define a clear problem statement. Ideate: many ideas first, then choose using the user\'s needs.',run(X){X.show('i');X.cap.textContent=''}}],
 quiz:[Q('t','What does a good problem statement include?',['The user, their need and why','Only the solution','A drawing','The price'],0,'It focuses on the user and their need.'),Q('t','Why do designers talk to users first?',['To understand their real needs','To sell the product','To avoid prototypes','To save paper'],0,'Empathy shows what really matters.'),
  Q('t','What is the aim of brainstorming?',['Generate many ideas','Choose the final design','Test the product','Write the instructions'],0,'Quantity helps you find better ideas.'),Q('t','How do you choose the best idea?',['Compare ideas with the user\'s needs','Choose the shortest idea','Choose the one drawn first','Vote randomly'],0,'The best idea meets the needs.')]});

/* ===== 4.3 Prototype, test and improve ===== */
SCENES.push({id:'4.3',act:'cad',title:'Prototype, test and improve',idea:'Cheap models find problems early',
 setup(ctx){
  const s=ctx.svg();const X={s,w:6,h:8,tip:0};const base=380;
  s.append(L(40,base,500,base,{stroke:'var(--muted)','stroke-width':3}));X.holder=S('g');s.append(X.holder);
  X.draw=(w,h,tip,col)=>{X.holder.innerHTML='';const pw=w*20,ph=h*20,x0=270-pw/2;const g=S('g',{transform:`rotate(${tip||0} ${x0+pw} ${base})`});g.append(R(x0,base-ph,pw,ph,{rx:6,fill:col||'#e0b070','stroke-width':3,opacity:.9}));const n=5;for(let i=0;i<n;i++){const x=x0+12+i*((pw-24)/(n-1)),top=Math.min(base-ph-40,base-ph+14),len=Math.max(150,ph+50);g.append(L(x,base-12,x+ (i-2)*6,base-12-Math.max(ph*0.7+40,100),{stroke:['#e5484d','#2f64d8','#2faa4a','#e0911c','#8a63d2'][i],'stroke-width':6}))}
    X.holder.append(g);X.holder.append(T(270,base+28,`${w} cm wide`,{'font-size':16,fill:'var(--muted)'}),T(x0-20,base-ph/2,`${h} cm`,{'font-size':16,fill:'var(--muted)','text-anchor':'end'}))};
  X.crit=S('g');[['Stable','base at least 8 cm wide'],['Holds 5 pens','height at least 9 cm'],['Fits in a bag','width 12 cm or less']].forEach((c,i)=>{X.crit.append(R(540,70+i*92,230,76,{rx:14,fill:'var(--paper)','stroke-width':2.5}),T(655,102+i*92,c[0],{'font-size':19,'font-family':'Fredoka,sans-serif'}),T(655,128+i*92,c[1],{'font-size':14,fill:'var(--muted)'}));const m=T(745,106+i*92,'',{'font-size':26});X.crit.append(m)});s.append(X.crit);X.marks=[...X.crit.querySelectorAll('text')].filter((_,i)=>i%3===2);
  X.fb=T(270,60,'',{'font-size':21,fill:'var(--accent)','font-family':'Fredoka,sans-serif'});s.append(X.fb);
  X.eval=(w,h)=>[w>=8,h>=9,w<=12];X.mark=r=>X.marks.forEach((m,i)=>{m.textContent=r?(r[i]?'✓':'✗'):'';m.setAttribute('fill',r&&r[i]?'var(--good)':'var(--bad)')});
  X.vers=S('g',{opacity:0});[['v1: paper','cheap and quick',60,'#f3efe0'],['v2: cardboard','stronger',240,'#e0b070'],['v3: 3D printed','final',420,'#58b868']].forEach((v,i)=>{X.vers.append(R(v[2],150,150,120,{rx:12,fill:v[3],'stroke-width':3}),T(v[2]+75,310,v[0],{'font-size':17,'font-family':'Fredoka,sans-serif'}),T(v[2]+75,332,v[1],{'font-size':14,fill:'var(--muted)'}))});s.append(X.vers);
  X.view=m=>{X.holder.setAttribute('opacity',m==='h'?1:0);X.crit.setAttribute('opacity',m==='h'?1:0);X.vers.setAttribute('opacity',m==='v'?1:0)};X.draw(6,8);X.view('h');return X},
 steps:[
  {k:'watch',run(X,ctx){X.view('v');X.fb.textContent='';[...X.vers.children].forEach(c=>c.setAttribute('opacity',0));[...X.vers.children].forEach((c,i)=>ctx.after(700+Math.floor(i/3)*2800,()=>c.setAttribute('opacity',1)))}},
  {k:'watch',run(X,ctx){X.view('h');X.mark(null);X.draw(6,8);X.fb.textContent='Test v1: 6 cm wide, 8 cm tall';ctx.after(1200,()=>{X.draw(6,8,18);X.mark(X.eval(6,8));X.fb.textContent='Feedback: it tips over! Widen the base.'});ctx.after(5200,()=>{X.draw(10,8,0);X.mark(X.eval(10,8));X.fb.textContent='v2: stable, but the pens are too tall for it'});ctx.after(9200,()=>{X.draw(10,11,0,'#58b868');X.mark(X.eval(10,11));X.fb.textContent='v3: all tests passed!'})}},
  {k:'predict',q:'Why make a quick, cheap prototype first?',opts:['To find problems early, before spending lots of time and money','Because it looks the best','So we never need to test','To avoid listening to users'],ans:0,why:'A rough prototype shows what is wrong quickly and cheaply, so you can improve before the final version.',run(X){X.view('v');[...X.vers.children].forEach(c=>c.setAttribute('opacity',1))}},
  {k:'try',build(X,ctx){X.view('h');X.mark(null);const h=ctx.panel;let w=6,hh=8,won=false;X.draw(w,hh);X.fb.textContent='Your prototype';
   const fb=H('div',{class:'fb info'},'Set the size so all three tests pass, then press Test.');
   const sw=sliderRow('Width',4,14,6,1,v=>{w=v;X.draw(w,hh);X.mark(null)},' cm'),sh=sliderRow('Height',5,16,8,1,v=>{hh=v;X.draw(w,hh);X.mark(null)},' cm');
   const go=H('button',{class:'btn small',onclick:()=>{const r=X.eval(w,hh);X.mark(r);X.draw(w,hh,r[0]?0:18);const pass=r.every(Boolean);fb.className='fb '+(pass?'good':'bad');fb.textContent=pass?'All tests passed! This prototype meets the needs.':(!r[0]?'It tips over: make the base wider. ':'')+(!r[1]?'The pens do not fit: make it taller. ':'')+(!r[2]?'Too wide for the bag: make it narrower.':'');X.fb.textContent=pass?'Passed!':'Needs improving';if(pass&&!won){won=true;cheer(true);ctx.done()}else if(!pass)cheer(false)}},'Test it');
   h.append(sw.el,sh.el,go,fb)}},
  {k:'sum',take:'A prototype is a quick, cheap model. Test it with users, learn what to fix, improve it, and test again.',run(X){X.view('h');X.draw(10,11,0,'#58b868');X.mark([true,true,true]);X.fb.textContent=''}}],
 quiz:[Q('t','What is a prototype?',['An early model used to test an idea','The final product','A report','A bill'],0,'Prototypes are rough models made to test ideas.'),Q('t','Why do designers test prototypes with users?',['To find out what to improve','To skip making more','To save the idea','To hide problems'],0,'Feedback shows problems and needs.'),
  Q('t','The prototype keeps tipping over. What is the best improvement?',['Make the base wider','Make it taller','Add more pens','Paint it'],0,'A wider base is more stable.'),Q('t','Which is the best material for a first, rough prototype?',['Paper or cardboard','Solid gold','Steel','Glass'],0,'Cheap, quick materials make early prototypes easy to change.')]});

/* ===== 4.4 CAD and Tinkercad ===== */
SCENES.push({id:'4.4',act:'cad',title:'CAD and Tinkercad',idea:'Shapes, solid and hole, group',
 setup(ctx){
  const s=ctx.svg();const X={s,st:{box:false,cyl:false,hole:false,moved:false,grouped:false}};
  s.append(R(10,10,780,430,{rx:14,fill:'#f4f7fb','stroke-width':2.5}),R(10,10,780,36,{rx:14,fill:'#2b6cb0'}),T(70,35,'Tinkercad',{'font-size':17,fill:'#fff','font-family':'Fredoka,sans-serif'}),T(400,35,'Design 1  (a mock-up)',{'font-size':14,fill:'#cfe0ff'}));
  X.panel=S('g');X.panel.append(R(20,56,130,370,{rx:10,fill:'#fff','stroke-width':2}),T(85,80,'Basic Shapes',{'font-size':14,fill:'var(--muted)'}),R(46,96,36,36,{rx:3,fill:'#e5484d','stroke-width':2}),C(114,114,18,{fill:'#e0911c','stroke-width':2}),C(65,170,18,{fill:'#2f64d8','stroke-width':2}),S('polygon',{points:'114,152 134,188 94,188',fill:'#2faa4a',stroke:'var(--ink)','stroke-width':2}),T(64,226,'box',{'font-size':12}),T(114,226,'cylinder',{'font-size':12}));s.append(X.panel);
  X.wp=S('g');X.wp.append(S('polygon',{points:'190,380 600,380 740,270 330,270',fill:'#cfe0fb',stroke:'#7aa3e6','stroke-width':2}));for(let i=1;i<10;i++){const t=i/10;X.wp.append(L(190+410*t,380,330+410*t,270,{stroke:'#9bbcf0','stroke-width':1.2}),L(190+140*t,380-110*t,600+140*t,380-110*t,{stroke:'#9bbcf0','stroke-width':1.2}))}X.wp.append(T(460,408,'Workplane',{'font-size':15,fill:'#5b7fc7'}));s.append(X.wp);
  X.obj=S('g');s.append(X.obj);X.info=T(470,70,'',{'font-size':17,fill:'var(--accent)','font-family':'Fredoka,sans-serif'});s.append(X.info);
  const bx=(g,x,y,w,h,d,dy,c1,c2,c3,op)=>{g.append(S('polygon',{points:`${x},${y} ${x+w},${y} ${x+w+d},${y-dy} ${x+d},${y-dy}`,fill:c2,stroke:'var(--ink)','stroke-width':2,opacity:op||1}),S('polygon',{points:`${x+w},${y} ${x+w+d},${y-dy} ${x+w+d},${y-dy+h} ${x+w},${y+h}`,fill:c3,stroke:'var(--ink)','stroke-width':2,opacity:op||1}),R(x,y,w,h,{rx:0,fill:c1,'stroke-width':2,opacity:op||1}))};
  X.draw=()=>{X.obj.innerHTML='';const st=X.st;const BX=300,BY=315;
    if(st.box){if(st.grouped&&st.hole&&st.moved){bx(X.obj,BX,BY,160,36,60,40,'#e5484d','#f06b70','#c23a3f');X.obj.append(S('ellipse',{cx:BX+86,cy:BY-20,rx:24,ry:10,fill:'#cfe0fb',stroke:'var(--ink)','stroke-width':2.5}),S('path',{d:`M${BX+62} ${BY-20}V${BY-13}A24 10 0 0 0 ${BX+110} ${BY-13}V${BY-20}`,fill:'#a83a3f',stroke:'none',opacity:.7}))}
      else bx(X.obj,BX,BY,160,36,60,40,'#e5484d','#f06b70','#c23a3f')}
    if(st.cyl){const cx=st.moved?BX+86:600,cy=st.moved?BY-18:330,hh=st.moved?50:44;const hole=st.hole,fill=hole?'url(#hs)':'#e0911c';
      if(!(st.grouped&&hole&&st.moved)){const defs=S('defs');const pat=S('pattern',{id:'hs',width:8,height:8,patternUnits:'userSpaceOnUse',patternTransform:'rotate(45)'});pat.append(R(0,0,8,8,{rx:0,fill:'#cfd4dc',stroke:'none'}),R(0,0,4,8,{rx:0,fill:'#8d96a5',stroke:'none'}));defs.append(pat);X.obj.append(defs,S('path',{d:`M${cx-24} ${cy}V${cy-hh}A24 10 0 0 1 ${cx+24} ${cy-hh}V${cy}A24 10 0 0 1 ${cx-24} ${cy}Z`,fill,stroke:'var(--ink)','stroke-width':2.5,opacity:hole?.85:1}),S('ellipse',{cx,cy:cy-hh,rx:24,ry:10,fill:hole?'#e9edf3':'#f2b05e',stroke:'var(--ink)','stroke-width':2.5}))}}
    };
  X.msg=t=>{X.info.textContent=t};X.draw();return X},
 steps:[
  {k:'watch',run(X,ctx){X.st={box:false,cyl:false,hole:false,moved:false,grouped:false};X.draw();X.msg('CAD = Computer-Aided Design');ctx.after(1800,()=>{X.st.box=true;X.draw();X.msg('Drag a shape onto the workplane')});ctx.after(5200,()=>X.msg('Resize with the white handles, rotate with the arrows'));ctx.after(9000,()=>X.msg('Shapes can be solid or hole')) }},
  {k:'watch',run(X,ctx){X.st={box:true,cyl:true,hole:false,moved:false,grouped:false};X.draw();X.msg('A box and a solid cylinder');ctx.after(2500,()=>{X.st.hole=true;X.draw();X.msg('Set the cylinder to Hole (striped)')});ctx.after(5200,()=>{X.st.moved=true;X.draw();X.msg('Move it into the box')});ctx.after(8000,()=>{X.st.grouped=true;X.draw();X.msg('Group: the hole cuts out of the box!')})}},
  {k:'predict',q:'You want a hole in a box. How should the cylinder be set before you group the shapes?',opts:['Set to Hole','Set to Solid','Make it bigger','Delete the box'],ans:0,why:'A hole shape removes material from any solid it overlaps when you group them.',run(X){X.st={box:true,cyl:true,hole:false,moved:true,grouped:false};X.draw();X.msg('')},reveal(X){X.st.hole=true;X.st.grouped=true;X.draw()}},
  {k:'try',build(X,ctx){const h=ctx.panel;X.st={box:false,cyl:false,hole:false,moved:false,grouped:false};X.draw();X.msg('Make a keyring tag with a hole');
   const fb=H('div',{class:'fb info'},'Press the buttons to build a keyring tag: a box with a hole near one end.');const bt={};let won=false;
   const mk=(id,label,fn)=>{const b=H('button',{class:'btn small ghost',onclick:fn},label);bt[id]=b;return b};
   const upd=()=>{const s=X.st;bt.box.disabled=s.box;bt.cyl.disabled=s.cyl||!s.box;bt.hole.disabled=!s.cyl||s.hole||s.grouped;bt.move.disabled=!s.cyl||s.moved||s.grouped;bt.group.disabled=!s.moved||s.grouped};
   const bits=[mk('box','1. Add a box',()=>{X.st.box=true;X.draw();upd()}),mk('cyl','2. Add a cylinder',()=>{X.st.cyl=true;X.draw();upd()}),mk('hole','3. Set the cylinder to Hole',()=>{X.st.hole=true;X.draw();upd()}),mk('move','4. Move it onto the box',()=>{X.st.moved=true;X.draw();upd()}),
     mk('group','5. Group',()=>{X.st.grouped=true;X.draw();upd();if(X.st.hole){fb.className='fb good';fb.textContent='A keyring tag with a hole! The hole shape cut into the solid box.';X.msg('Keyring tag done!');if(!won){won=true;cheer(true);ctx.done()}}else{fb.className='fb bad';fb.textContent='Both shapes were solid, so grouping just joined them into one lump. Press Start again, and set the cylinder to Hole before grouping.';cheer(false)}}),
     H('button',{class:'btn small',onclick:()=>{X.st={box:false,cyl:false,hole:false,moved:false,grouped:false};X.draw();fb.className='fb info';fb.textContent='Start again.';upd()}},'Start again')];
   h.append(H('div',{class:'opts'},...bits),fb);upd()}},
  {k:'sum',take:'CAD means computer-aided design. In Tinkercad you build on the workplane with shapes. Make a hole by setting a shape to Hole, then group it with the solid.',run(X){X.st={box:true,cyl:true,hole:true,moved:true,grouped:true};X.draw();X.msg('Hole + Solid + Group')}}],
 quiz:[Q('t','What does CAD stand for?',['Computer-aided design','Colour and drawing','Copy and delete','Control and data'],0,'CAD means computer-aided design.'),Q('t','In Tinkercad, what is the flat grid you build on called?',['The workplane','The canvas','The ruler','The cube'],0,'Shapes are placed on the workplane.'),
  Q('t','To cut a hole in a box, what do you do with the cylinder?',['Set it to Hole, then group it with the box','Colour it grey','Make it smaller','Delete it'],0,'Hole shapes remove material when grouped.'),Q('t','What does Group do?',['Combines shapes into one object','Deletes all shapes','Changes the colour','Saves the file'],0,'Grouping joins shapes, and holes cut out of solids.')]});
